#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     MotorControllers, sensorNone)
#pragma config(Sensor, S2,     TouchSensor,    sensorTouch)
#pragma config(Sensor, S3,     SMUX1,          sensorI2CCustom)
#pragma config(Sensor, S4,     SMUX2,          sensorI2CCustom)
#pragma config(Motor,  motorB,          Kicker,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Dribbler,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFL,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Sensor Setup:

S1: MotorControllers (TETRIX Motor Controllers)
S2: KickerTouch
S3: SMUX1 (HiTechnic Sensor Multiplexer)
		1 - IRBack (HiTechnic IRSeeker V2)
		2 - IRFront (HiTechnic IRSeeker V2)
		3 - USBack (Lego Ultrasonic Sensor)
		4 - USRight (Lego Ultrasonic Sensor)
S4: SMUX2 (MindSensors Port Splitter)
		1 - Colour (HiTechnic Color Sensor V2)
		2 - HaveBaller (Lego Touch Sensor)
		3 - Compass (HiTechnic Compass Sensor)
*/

#include "common.h"
#include "hitechnic-sensormux.h"
#include "hitechnic-irseeker-v2.h"
#include "hitechnic-compass.h"
#include "hitechnic-colour-v2.h"
#include "lego-touch.h"
#include "lego-ultrasound.h"

const tMUXSensor IRFront = msensor_S3_1;
const tMUXSensor HaveBaller = msensor_S3_2;
const tMUXSensor USBack = msensor_S3_3;
const tMUXSensor Colour = msensor_S3_4;
const tMUXSensor Compass = msensor_S4_4;

#define ST  0
#define F   1
#define FR  2
#define R   3
#define BR  4
#define B   5
#define BL  6
#define L   7
#define FL  8
#define CW  9
#define CC  10

#define nbound 13
#define rbound 45
#define bbound 30
#define whiteThreshold 200

#define power 25
#define turnPower 10

  long currentRed = 0;
  long currentGreen = 0;
  long currentBlue = 0;
  //long gRed = 0;
  //long gGreen = 0;
  //long gBlue = 0;
  int _target = 0;

	//y	x								(   motorFL,   	motorFR,	  motorBR,	  motorBL)
int const mov[11][4]={{					0,			    0,     	 		0, 	        0},  //ST
                      {		 -power,			power,			power,		 -power},  //F
                      {		 -power,					0,			power,					0},  //FR
                      {		 -power,		 -power,			power,			power},  //R
                      {					0,		 -power,					0,			power},  //BR
                      {			power,		 -power,		 -power,			power},  //B
                      {			power,				  0,		 -power,					0},  //BL
                      {			power,			power,		 -power,		 -power},  //L
                      {					0,			power,					0,		- power},  //FL
                      {-turnPower, -turnPower, -turnPower, -turnPower},  //CW
                      {	turnPower,	turnPower,  turnPower,  turnPower}}; //CC


void move(int dir){
	motor[motorFL]=mov[dir][0];
	motor[motorFR]=mov[dir][1];
	motor[motorBR]=mov[dir][2];
	motor[motorBL]=mov[dir][3];
}

int calc(){
	int length = USreadDist(USBack);
  int width = USreadDist(USRight);
  bool haveBall = TSreadState(HaveBaller);
  int frontIRValue = HTIRS2readACDir(IRFront);
  int currentRelCompass = HTMCreadRelativeHeading(Compass);
  HTCS2readRGB(Colour, currentRed, currentGreen, currentBlue);
  bool isWhite = (currentRed > whiteThreshold && currentGreen > whiteThreshold && currentBlue > whiteThreshold);

  nxtDisplayTextLine(2, "Com:   %4d", currentRelCompass);
	nxtDisplayTextLine(3, "IR:   %4d", frontIRValue);
	nxtDisplayTextLine(4, "Len:   %4d", length);
	nxtDisplayTextLine(5, "Wid:   %4d", width);
	nxtDisplayTextLine(6, "Ball:   %4d", haveBall);
	if(isWhite){
		nxtDisplayTextLine(7, "White:   Yes");
	}
	else{
		nxtDisplayTextLine(7, "White:   No");
	}


  else{
  	if(isWhite){
  		if(width <= rbound){
  			return FL;
  		}
  		else{
  			return FR;
  		}
  	}
  	else{
  		if(!haveBall){
				switch(frontIRValue){
					case 1:
						return B;
						break;
					case 2:
						return BL;
						break;
					case 3:
						return L;
						break;
					case 4:
						return FL;
						break;
					case 5:
						return F;
						break;
					case 6:
						return FR;
						break;
					case 7:
						return R;
						break;
					case 8:
						return BR;
						break;
					case 9:
						return B;
						break;
				}
  		}
  		else{
				else{
					if(width < rgoalbound){
						move(FL);
						wait10Msec(100);
						return FL;
					}
					else if(width < lgoalbound){
						move(FL);
						wait10Msec(100);
						return F;
					}
					else{
						move(FL);
						wait10Msec(100);
						return FR;
					}
				}
			}
		}
	}
}



void calibrate(){
	eraseDisplay();
	//while(nNxtButtonPressed != kEnterButton) {
	//	nxtDisplayCenteredTextLine(0, "Robonauts");
	//	nxtDisplayCenteredTextLine(1, "Defense");
	//	nxtDisplayCenteredTextLine(3, "Calibrate Green");
	//	nxtDisplayCenteredTextLine(6, "Press Enter");
 //	}
 //	eraseDisplay();
 // HTCS2readRGB(Colour, gRed, gGreen, gBlue);
 // wait10Msec(20);
  //while(nNxtButtonPressed != kEnterButton) {
		//nxtDisplayCenteredTextLine(0, "Robonauts");
		//nxtDisplayCenteredTextLine(1, "Defense");
		//nxtDisplayCenteredBigTextLine(3, "Calibrate Black");
		//nxtDisplayCenteredTextLine(6, "Press Enter");
  //	eraseDisplay();
 	//}
 	//HTCS2readRGB(Colour, bRed, bGreen, bBlue);
  //wait10Msec(20);
  //while(nNxtButtonPressed != kEnterButton) {
		//nxtDisplayCenteredTextLine(0, "Robonauts");
		//nxtDisplayCenteredTextLine(1, "Defense");
		//nxtDisplayCenteredBigTextLine(3, "Calibrate White");
		//nxtDisplayCenteredTextLine(6, "Press Enter");
  //	eraseDisplay();
 	//}
 	//HTCS2readRGB(Colour, wRed, wGreen, wBlue);
  //wait10Msec(20);
  while(nNxtButtonPressed != kEnterButton) {
		nxtDisplayCenteredTextLine(0, "Robonauts");
		nxtDisplayCenteredTextLine(1, "Offense");
		nxtDisplayCenteredTextLine(3, "Calibrate Compass");
		nxtDisplayTextLine(4, "Abs:   %4d", HTMCreadHeading(Compass));
		nxtDisplayCenteredTextLine(6, "Press Enter");
 	}
 	eraseDisplay();
 	nxtDisplayTextLine(2, "Setting");
  nxtDisplayTextLine(3, "target");
  wait1Msec(500);
  // Set the current heading as the value for the offset to be used as the
  // new zero-point for the relative heading returned by
  // HTMCreadRelativeHeading()
  _target = HTMCsetTarget(Compass);
  PlaySound(soundBlip);
  while(bSoundActive){
  	EndTimeSlice();
  }
  eraseDisplay();
  while(nNxtButtonPressed != kEnterButton) {
		nxtDisplayCenteredTextLine(0, "Robonauts");
		nxtDisplayCenteredTextLine(1, "Offense");
		nxtDisplayCenteredBigTextLine(3, "START ROBOT");
		nxtDisplayCenteredTextLine(6, "Press Enter");
 	}
 	eraseDisplay();
}


task main(){
	calibrate();
	motor[Dribbler] = 100;
	while(true){
		move(calc());
		wait1Msec(100);
	}
}
