#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFL,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                            - FOR Loop -                                                *|
|*                                       ROBOTC on NXT + TETRIX                                           *|
|*                                                                                                        *|
|*  This program runs your TETRIX robot in a square five times.                                           *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  Remember to use 'Robot -> Motors and Sensors Setup'to set up your motor configuration.          *|
|*    2)  If using kit TETRIX bot, remember to reverse Motor E in 'Motor and Sensor Setup'.               *|
|*    3)  You may need to change the wait times used to achieve a 90 degree turn.  Experiment to find     *|
|*        the perfect values and your robot should end facing the same direction that it started.         *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port 1                  none                TETRIX Controller   TETRIX                              *|
|*    Port 1 - Motor 1        motorD              12V                 Right motor                         *|
|*    Port 1 - Motor 2        motorE              12V                 Left motor                          *|
\*---------------------------------------------------------------------------------------------------4246-*/


task main()
{
	int power = 10;
   //a for loop is declared that: intializes i equal to zero
   //continues to run under the condition i is less than 20
   //and increments i by one after each iteration
			motor[motorBL] = power;    // Motor D is run at a	75 power level.
      motor[motorFL] = power;
      motor[motorBR] = -power;    // Motor D is run at a	75 power level.
      motor[motorFR] = -power;
      wait1Msec(1500);

      motor[motorBL] = power;    // Motor D is run at a	75 power level.
      motor[motorFL] = 0;
      motor[motorBR] = -power;    // Motor D is run at a	75 power level.
      motor[motorFR] = 0;
      wait1Msec(1500);

      motor[motorBL] = -power;    // Motor D is run at a	75 power level.
      motor[motorFL] = -power;
      motor[motorBR] = power;    // Motor D is run at a	75 power level.
      motor[motorFR] = power;
      wait1Msec(1500);

motor[motorBL] = power;    // Motor D is run at a	75 power level.
      motor[motorFL] = power;
      motor[motorBR] = power;    // Motor D is run at a	75 power level.
      motor[motorFR] = power;
      wait1Msec(1500);

      motor[motorBL] = -power;    // Motor D is run at a	75 power level.
      motor[motorFL] = -power;
      motor[motorBR] = -power;    // Motor D is run at a	75 power level.
      motor[motorFR] = -power;
      wait1Msec(1500);
      }
