#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     MotorControllers, sensorI2CMuxController)
#pragma config(Sensor, S2,     HaveBaller,     sensorTouch)
#pragma config(Sensor, S3,     SMUX1,          sensorI2CCustom)
#pragma config(Sensor, S4,     SMUX2,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFL,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Sensor Setup:

S1: MotorControllers (TETRIX Motor Controllers)
S2: HaveBaller (Lego Touch Sensor)55
S3: SplitterA (MindSensors Port Splitter)
		- USFront (Lego Ultrasonic Sensor)
		- IRFront (HiTechnic IRSeeker V2)
		- Colour (HiTechnic Color Sensor)
S4: SplitterB (MindSensors Port Splitter)
		- USRight (Lego Ultrasonic Sensor)
		- IRBack (HiTechnic IRSeeker V2)
		- Compass (HiTechnic Compass Sensor)
*/

#include "common.h"
#include "hitechnic-irseeker-v2.h"
#include "hitechnic-compass.h"

#define ST  0
#define F   1
#define FR  2
#define R   3
#define BR  4
#define B   5
#define BL  6
#define L   7
#define FL  8
#define CW  9
#define CC  10

#define nbound 30
#define rbound 30
#define lbound 152
#define fbound 213
#define bbound 30

#define power 1
#define turnPower 1


										//(   motorFL,   	motorFR,	  motorBR,	  motorBL)
int const mov[11][4]={{				0,			    0,     	 		0, 	        0},  //ST
                      {		 -1.4,		 			1,					1,		 	-1.4},  //F
                      {		 -1.4,					0,					1,					0},  //FR
                      {		 -1.4,		 			-1,					1,			1.4},  //R
                      {				0,		 			-1,					0,			1.4},  //BR
                      {			1.4,		 			-1,					-1,			1.4},  //B
                      {			1.4,				  0,					-1,				0},  //BL
                      {			1.4,					1,					-1,		 -1.4},  //L
                      {				0,					1,					0,		-1.4},  //FL
                      {		 -1.4,			 -1, 				 -1, -1.4}, //CW
                      {			1.4,				1,	  			1,  1.4}}; //CC


//void move(int dir){
	//motor[motorFL]=mov[dir][0];
//	motor[motorFR]=mov[dir][1];
//	motor[motorBR]=mov[dir][2];
//	motor[motorBL]=mov[dir][3];
//}

void move(int dir, int motorPow){
	motor[motorFL]= (int)( mov[dir][0] * motorPow);
	motor[motorFR]= (int)(mov[dir][1] * motorPow / 1.4);
	motor[motorBR]= (int)(mov[dir][2] * motorPow) / 1.4;
	motor[motorBL]= (int)(mov[dir][3] * motorPow);
	wait1Msec(50);
	motor[motorFL]= (int)( mov[dir][0] * motorPow);
	motor[motorFR]= (int)(mov[dir][1] * motorPow);
	motor[motorBR]= (int)(mov[dir][2] * motorPow);
	motor[motorBL]= (int)(mov[dir][3] * motorPow);
}

task main(){
	move(R, 30);
	wait10Msec(400);

	//wait10Msec(200);
	//move(CC);
	//wait10Msec(200);
	//move(F);
	//wait10Msec(200);
	//move(R);
	//wait10Msec(200);
	//move(BL);
	//wait10Msec(200);
}

//fl = BR
//bl = fl
//br=bl
//baka

// BL = 56
// FL = 57
// FR = 58
// BR = 45
