#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     MotorControllers, sensorI2CMuxController)
#pragma config(Sensor, S2,     TouchSensor,    sensorTouch)
#pragma config(Sensor, S3,     SMUX1,          sensorI2CCustom)
#pragma config(Sensor, S4,     SMUX2,          sensorI2CCustom)
#pragma config(Motor,  motorB,          Kicker,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Dribbler,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFL,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Sensor Setup:

S1: MotorControllers (TETRIX Motor Controllers)
S2: KickerTouch
S3: SMUX1 (HiTechnic Sensor Multiplexer)
		1 - IRBack (HiTechnic IRSeeker V2)
		2 - IRFront (HiTechnic IRSeeker V2)
		3 - USBack (Lego Ultrasonic Sensor)
		4 - USRight (Lego Ultrasonic Sensor)
S4: SMUX2 (MindSensors Port Splitter)
		1 - Colour (HiTechnic Color Sensor V2)
		2 - HaveBaller (Lego Touch Sensor)
		3	- Compass (HiTechnic Compass Sensor)
*/

#include "common.h"
#include "hitechnic-sensormux.h"
#include "hitechnic-irseeker-v2.h"
#include "hitechnic-compass.h"
#include "hitechnic-colour-v2.h"

const tMUXSensor IRBack = msensor_S3_1;
const tMUXSensor IRFront = msensor_S3_2;
const tMUXSensor USBack = msensor_S3_3;
const tMUXSensor USRight = msensor_S3_4;
const tMUXSensor Colour = msensor_S4_1;
const tMUXSensor HaveBaller = msensor_S4_2;
const tMUXSensor Compass = msensor_S4_3;

#define ST  0
#define F   1
#define FR  2
#define R   3
#define BR  4
#define B   5
#define BL  6
#define L   7
#define FL  8
#define CW  9
#define CC  10

#define nbound 30
#define rbound 30
#define lbound 152
#define fbound 213
#define bbound 30
#define rgoalbound 61
#define lgoalbound 152
#define widthAdjust 25

#define whiteThreshold 200

#define power 15
#define turnPower 5

	long currentRed = 0;
  long currentGreen = 0;
  long currentBlue = 0;
	long gRed = 0;
  long gGreen = 0;
  long gBlue = 0;
  long wRed = 0;
  long wGreen = 0;
  long wBlue = 0;
  long bRed = 0;
  long bGreen = 0;
  long bBlue = 0;
  int _target = 0;

							//y	x		(   motorFL,   	motorFR,	  motorBR,	  motorBL)
int const mov[11][4]={{					0,			    0,     	 		0, 	        0},  //ST
                      {		 -power,			power,			power,		 -power},  //F
                      {		 -power,					0,			power,					0},  //FR
                      {		 -power,		 -power,			power,			power},  //R
                      {					0,		 -power,					0,			power},  //BR
                      {			power,		 -power,		 -power,			power},  //B
                      {			power,				  0,		 -power,					0},  //BL
                      {			power,			power,		 -power,		 -power},  //L
                      {					0,			power,					0,		- power},  //FL
                      {-turnPower, -turnPower, -turnPower, -turnPower},  //CW
                      {	turnPower,	turnPower,  turnPower,  turnPower}}; //CC

int calc(){
  return B;
}



void move(int dir){
	motor[motorFL]=mov[dir][0];
	motor[motorFR]=mov[dir][1];
	motor[motorBR]=mov[dir][2];
	motor[motorBL]=mov[dir][3];
}

task main(){
	while(true){
		move(calc());
	}
}
